import localFont from 'next/font/local';

import type { Metadata } from 'next';

import './globals.css';

import { AppProvider } from '@/app/_providers/app-provider';
import { DarkContainer } from '@/widgets/dark';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});
const jetBrainsMono = localFont({
  src: './fonts/JetBrainsMono-Regular.woff2',
  variable: '--font-jetbrains-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jetBrainsMono.variable} antialiased`}
      >
        <AppProvider>
          <DarkContainer>{children}</DarkContainer>
        </AppProvider>
      </body>
    </html>
  );
}
